### ISSUE TITLE
delete Unicode character

### ISSUE THREAD

**Issue by hrichiez** [StevenPG/ProjectManagement#58]
delete unicode character that gets attached to the user data in the database.

**Comment by StevenPG** [comment]
Tyler removed the unicode characters from the titles

**Comment by StevenPG** [comment]
Currently investigating the generic character being added when a project is created.

**Comment by StevenPG** [comment]
BUG FOUND:
Because the intial projectlist is empty, python denotes the empty field as None. Since we use the substring method to remove the u' ' normally, we apply this to None. This happens to leave only an n. This n is the set and a pair of - are added, creating the visual bug.

I'm attempting to remove this by adding extra checking for empty project lists.

**Comment by StevenPG** [comment]
Bug was fixed by checking for an empty projectlist.
